'use strict';

const apiProtocol = 'https:';
const apiDomain = 'api.volvocars.com';
const oAuthDomain = 'volvoid.eu.volvocars.com';
const apiTimeout = 10000;

const commands = {
    CLIMATIZATION_START: 'CLIMATIZATION_START',
    CLIMATIZATION_STOP: 'CLIMATIZATION_STOP',
    ENGINE_START: 'ENGINE_START',
    ENGINE_STOP: 'ENGINE_STOP',
    FLASH: 'FLASH',
    HONK: 'HONK',
    HONK_AND_FLASH: 'HONK_AND_FLASH',
    LOCK: 'LOCK',
    LOCK_REDUCED_GUARD: 'LOCK_REDUCED_GUARD',
    UNLOCK: 'UNLOCK',
}

const vehicleType = {
    ICE: 'ICE',
    HYBRID: 'HYBRID',
    ELECTRIC: 'ELECTRIC'
};

const chargingSystemStatus = {
    CHARGING_SYSTEM_CHARGING: 'CHARGING_SYSTEM_CHARGING',
    CHARGING_SYSTEM_IDLE: 'CHARGING_SYSTEM_IDLE',
    CHARGING_SYSTEM_DONE: 'CHARGING_SYSTEM_DONE',
    CHARGING_SYSTEM_FAULT: 'CHARGING_SYSTEM_FAULT',
    CHARGING_SYSTEM_SCHEDULED: 'CHARGING_SYSTEM_SCHEDULED',
    CHARGING_SYSTEM_UNSPECIFIED: 'CHARGING_SYSTEM_UNSPECIFIED'
};

const location = {
    HOME: 'home',
    AWAY: 'away',
    UNKNOWN: 'unknown'
}

const warningValues = [
    'TOO_LOW',
    'SERVICE_REQUIRED',
    'TOO_HIGH',
    'UNKNOWN_WARNING',
    'REGULAR_MAINTENANCE_ALMOST_TIME_FOR_SERVICE',
    'ENGINE_HOURS_ALMOST_TIME_FOR_SERVICE',
    'DISTANCE_DRIVEN_ALMOST_TIME_FOR_SERVICE',
    'REGULAR_MAINTENANCE_TIME_FOR_SERVICE',
    'ENGINE_HOURS_TIME_FOR_SERVICE',
    'DISTANCE_DRIVEN_TIME_FOR_SERVICE',
    'REGULAR_MAINTENANCE_OVERDUE_FOR_SERVICE',
    'ENGINE_HOURS_OVERDUE_FOR_SERVICE',
    'DISTANCE_DRIVEN_OVERDUE_FOR_SERVICE',
    'VERY_LOW_PRESSURE',
    'LOW_PRESSURE',
    'HIGH_PRESSURE',
    'FAILURE'
]

module.exports = {
    apiProtocol,
    apiDomain,
    oAuthDomain,
    apiTimeout,
    commands,
    vehicleType,
    chargingSystemStatus,
    location,
    warningValues
}